openapi: 3.0.0
info:
  title: Splitwise Demo
  description: A demo splitwise backend for Setu's Interview process.
  version: 0.1.0

servers:
  - url: "http://host.docker.internal:8080"
    description: Local Server


paths:
  /:
    get:
      summary: Status Check
      description: Helps in checking if the server is up
      responses:
        '200':    # status code
          description: Ok
