name: build-test-check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'
      - run: sudo make install_ubuntu_dependencies
      - run: make install_dev_dependencies
      - run: make build
      - run: make test
      - run: make all-static-checks